export const AUTH_LOGIN='AUTH_LOGIN';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const CHANGE_SNACKBAR='CHANGE_SNACKBAR';
export const FETCH_LATEST_UPDATED_EVENTS_BY_ADMIN = 'FETCH_LATEST_UPDATED_EVENTS_BY_ADMIN';
export const FETCH_LATEST_UPDATED_ANNOUNCEMENTS_BY_ADMIN = 'FETCH_LATEST_UPDATED_ANNOUNCEMENTS_BY_ADMIN';
export const FETCH_ADMIN_MASJID = 'FETCH_ADMIN_MASJID';
export const GET_TIMINGS_BY_DATE_RANGE = 'GET_TIMINGS_BY_DATE_RANGE';


export const GET_USER_BY_ID = 'GET_USER_BY_ID';

export const UPDATE_USER_BY_ID_LEVEL1 = 'UPDATE_USER_BY_ID_LEVEL1';
export const UPDATE_USER_BY_ID_LEVEL2 = 'UPDATE_USER_BY_ID_LEVEL2';
export const UPDATE_USER_BY_ID_LEVEL3 = 'UPDATE_USER_BY_ID_LEVEL3';
export const UPDATE_USER_BY_ID_LEVEL4 = 'UPDATE_USER_BY_ID_LEVEL4';
export const UPDATE_USER_BY_ID_LEVEL5 = 'UPDATE_USER_BY_ID_LEVEL5';

