export const cities = [
  "Agra",
  "Ahmedabad",
  "Ajmer",
  "Alappuzha",
  "Aligarh",
  "Allahabad",
  "Alwar",
  "Ambala",
  "Amravati",
  "Amritsar",
  "Anand",
  "Anantapur",
  "Angul",
  "Aurangabad",
  "Azamgarh",
  "Bagalkot",
  "Bageshwar",
  "Bahraich",
  "Balaghat",
  "Ballia",
  "Balrampur",
  "Banaskantha",
  "Banda",
  "Bandipora",
  "Bangalore Rural",
  "Bangalore Urban",
  "Banka",
  "Bankura",
  "Banswara",
  "Barabanki",
  "Baramulla",
  "Baran",
  "Bareilly",
  "Bargarh",
  "Barmer",
  "Barnala",
  "Barpeta",
  "Barwani",
  "Bastar",
  "Basti",
  "Bathinda",
  "Beed",
  "Begusarai",
  "Belgaum",
  "Bellary",
  "Betul",
  "Bhadrak",
  "Bhagalpur",
  "Bhandara",
  "Bharatpur",
  "Bharuch",
  "Bhavnagar",
  "Bhilwara",
  "Bhind",
  "Bhiwani",
  "Bhopal",
  "Bhubaneswar",
  "Bhuj",
  "Bikaner",
  "Bilaspur",
  "Birbhum",
  "Bishnupur",
  "Bokaro",
  "Bongaigaon",
  "Boudh",
  "Budaun",
  "Bulandshahr",
  "Buldhana",
  "Bundi",
  "Burhanpur",
  "Buxar",
  "Cachar",
  "Central Delhi",
  "Chamarajanagar",
  "Chamba",
  "Chamoli",
  "Champawat",
  "Champhai",
  "Chandauli",
  "Chandel",
  "Chandigarh",
  "Chandrapur",
  "Changlang",
  "Chatra",
  "Chennai",
  "Chhatarpur",
  "Chhindwara",
  "Chikkaballapur",
  "Chikkamagaluru",
  "Chirang",
  "Chitradurga",
  "Chitrakoot",
  "Chittoor",
  "Chittorgarh",
  "Churachandpur",
  "Churu",
  "Coimbatore",
  "Cooch Behar",
  "Cuddalore",
  "Cuttack",
  "Dadra and Nagar Haveli",
  "Dahod",
  "Dakshina Kannada",
  "Daman",
  "Damoh",
  "Dantewada",
  "Darbhanga",
  "Darjeeling",
  "Darrang",
  "Datia",
  "Dausa",
  "Davanagere",
  "Dehradun",
  "Deoghar",
  "Deoria",
  "Devbhoomi Dwarka",
  "Dewas",
  "Dhalai",
  "Dhamtari",
  "Dhanbad",
  "Dhar",
  "Dharmapuri",
  "Dharwad",
  "Dhemaji",
  "Dhenkanal",
  "Dholpur",
  "Dhubri",
  "Dhule",
  "Dibang Valley",
  "Dibrugarh",
  "Dima Hasao",
  "Dimapur",
  "Dindigul",
  "Dindori",
  "Diu",
  "Doda",
  "Dumka",
  "Dungarpur",
  "East Champaran",
  "East Delhi",
  "East Garo Hills",
  "East Khasi Hills",
  "East Siang",
  "East Sikkim",
  "East Singhbhum",
  "Eluru",
  "Ernakulam",
  "Erode",
  "Etah",
  "Etawah",
  "Faizabad",
  "Faridabad",
  "Faridkot",
  "Farrukhabad",
  "Fatehabad",
  "Fatehgarh Sahib",
  "Fatehpur",
  "Fazilka",
  "Firozabad",
  "Firozpur",
  "Gadag",
  "Gadchiroli",
  "Gajapati",
  "Ganderbal",
  "Gandhinagar",
  "Ganganagar",
  "Ganjam",
  "Garhwa",
  "Gautam Buddha Nagar",
  "Gaya",
  "Ghaziabad",
  "Ghazipur",
  "Gir Somnath",
  "Giridih",
  "Goalpara",
  "Godda",
  "Golaghat",
  "Gonda",
  "Gondia",
  "Gopalganj",
  "Gorakhpur",
  "Gulbarga",
  "Gumla",
  "Guna",
  "Guntur",
  "Gurdaspur",
  "Gurgaon",
  "Gwalior",
  "Hailakandi",
  "Hailakandi",
  "Hamirpur",
  "Hanumangarh",
  "Harda",
  "Hardoi",
  "Haridwar",
  "Hassan",
  "Hathras",
  "Haveri",
  "Hazaribagh",
  "Hingoli",
  "Hissar",
  "Hooghly",
  "Hoshangabad",
  "Hoshiarpur",
  "Howrah",
  "Hyderabad",
  "Idukki",
  "Imphal East",
  "Imphal West",
  "Indore",
  "Jabalpur",
  "Jagatsinghapur",
  "Jaintia Hills",
  "Jaipur",
  "Jaisalmer",
  "Jajpur",
  "Jalandhar",
  "Jalaun",
  "Jalgaon",
  "Jalna",
  "Jalore",
  "Jalpaiguri",
  "Jammu",
  "Jamnagar",
  "Jamtara",
  "Jamui",
  "Janjgir-Champa",
  "Jashpur",
  "Jaunpur",
  "Jehanabad",
  "Jhabua",
  "Jhajjar",
  "Jhalawar",
  "Jhansi",
  "Jhargram",
  "Jharsuguda",
  "Jhunjhunu",
  "Jind",
  "Jodhpur",
  "Jorhat",
  "Junagadh",
  "Jyotiba Phule Nagar",
  "Kabirdham",
  "Kadapa",
  "Kaimur",
  "Kaithal",
  "Kakinada",
  "Kalahandi",
  "Kamrup",
  "Kamrup Metropolitan",
  "Kanchipuram",
  "Kandhamal",
  "Kangra",
  "Kanker",
  "Kannauj",
  "Kannur",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kanyakumari",
  "Kapurthala",
  "Karaikal",
  "Karauli",
  "Karbi Anglong",
  "Kargil",
  "Karimganj",
  "Karimnagar",
  "Karnal",
  "Karur",
  "Kasaragod",
  "Kathua",
  "Katihar",
  "Katni",
  "Kaushambi",
  "Kendrapara",
  "Kendujhar",
  "Khagaria",
  "Khammam",
  "Khandwa",
  "Khargone",
  "Kheda",
  "Khordha",
  "Khowai",
  "Khunti",
  "Kinnaur",
  "Kishanganj",
  "Kishtwar",
  "Kodagu",
  "Koderma",
  "Kohima",
  "Kokrajhar",
  "Kolar",
  "Kolasib",
  "Kolhapur",
  "Kolkata",
  "Kollam",
  "Koppal",
  "Koraput",
  "Korba",
  "Koriya",
  "Kota",
  "Kottayam",
  "Kozhikode",
  "Krishna",
  "Kulgam",
  "Kullu",
  "Kupwara",
  "Kurnool",
  "Kurukshetra",
  "Kurung Kumey",
  "Kushinagar",
  "Kutch",
  "Lahaul and Spiti",
  "Lakhimpur",
  "Lakhimpur Kheri",
  "Lakhisarai",
  "Lalitpur",
  "Latehar",
  "Latpanchar",
  "Latur",
  "Lawngtlai",
  "Leh",
  "Lohardaga",
  "Lohit",
  "Lower Dibang Valley",
  "Lower Subansiri",
  "Lucknow",
  "Ludhiana",
  "Madhepura",
  "Madhubani",
  "Madurai",
  "Mahamaya Nagar",
  "Maharajganj",
  "Mahasamund",
  "Mahbubnagar",
  "Mahe",
  "Mahendragarh",
  "Mahoba",
  "Mainpuri",
  "Malappuram",
  "Malda",
  "Malkangiri",
  "Mamit",
  "Mancherial",
  "Mandi",
  "Mandla",
  "Mandsaur",
  "Mandya",
  "Manipur",
  "Mansa",
  "Marigaon",
  "Mathura",
  "Mau",
  "Mayurbhanj",
  "Medak",
  "Meerut",
  "Mein",
  "Mokokchung",
  "Mon",
  "Moradabad",
  "Morena",
  "Morigaon",
  "Muktsar",
  "Mumbai City",
  "Mumbai Suburban",
  "Mungeli",
  "Munger",
  "Murshidabad",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysuru",
  "Nabarangpur",
  "Nadia",
  "Nagaon",
  "Nagapattinam",
  "Nagaur",
  "Nagpur",
  "Nainital",
  "Nalanda",
  "Nalbari",
  "Nalgonda",
  "Namakkal",
  "Namsai",
  "Nanded",
  "Nandurbar",
  "Narayanpur",
  "Narmada",
  "Narsinghpur",
  "Nashik",
  "Navsari",
  "Nawada",
  "Nawanshahr",
  "Nayagarh",
  "Neemuch",
  "Nellore",
  "New Delhi",
  "Nilgiris",
  "Nizamabad",
  "North 24 Parganas",
  "North Delhi",
  "North East Delhi",
  "North Garo Hills",
  "North Goa",
  "North Sikkim",
  "North Tripura",
  "North West Delhi",
  "Nuapada",
  "Osmanabad",
  "Pakur",
  "Palakkad",
  "Palamu",
  "Pali",
  "Palwal",
  "Panchkula",
  "Panchmahal",
  "Panchsheel Nagar district (Hapur)",
  "Pandharpur",
  "Panjim",
  "Panna",
  "Papum Pare",
  "Parbhani",
  "Pashchim Champaran",
  "Pashchim Singhbhum",
  "Patan",
  "Pathanamthitta",
  "Pathankot",
  "Patiala",
  "Patna",
  "Pauri Garhwal",
  "Perambalur",
  "Phek",
  "Piduguralla",
  "Pilibhit",
  "Pithoragarh",
  "Pollachi",
  "Poonch",
  "Porbandar",
  "Prakasam",
  "Pratapgarh",
  "Pudukkottai",
  "Pulwama",
  "Pune",
  "Purba Bardhaman",
  "Purba Singhbhum",
  "Puri",
  "Purnia",
  "Purulia",
  "Rae Bareli",
  "Raichur",
  "Raigad",
  "Raigarh",
  "Raipur",
  "Raisen",
  "Rajahmundry",
  "Rajgarh",
  "Rajkot",
  "Rajnandgaon",
  "Rajsamand",
  "Ramabai Nagar (Kanpur Dehat)",
  "Ramanagara",
  "Ramanathapuram",
  "Ramban",
  "Ramgarh",
  "Rampur",
  "Ranchi",
  "Rangareddy",
  "Ratlam",
  "Ratnagiri",
  "Rayagada",
  "Reasi",
  "Rewa",
  "Rewari",
  "Ri Bhoi",
  "Rohtak",
  "Rohtas",
  "Rudraprayag",
  "Rupnagar",
  "S.A.S. Nagar",
  "Sagar",
  "Saharanpur",
  "Saharsa",
  "Sahibganj",
  "Saiha",
  "Salem",
  "Samastipur",
  "Samba",
  "Sambalpur",
  "Sangli",
  "Sangrur",
  "Sant Kabir Nagar",
  "Sant Ravidas Nagar",
  "Saran",
  "SAS Nagar (Mohali)",
  "Satara",
  "Satna",
  "Sawai Madhopur",
  "Sehore",
  "Senapati",
  "Seoni",
  "Seraikela Kharsawan",
  "Serchhip",
  "Shahdol",
  "Shahjahanpur",
  "Shajapur",
  "Shamli",
  "Sheikhpura",
  "SHEOHAR",
"Sheopur",
"Siddharthnagar",
"Siddipet",
"Sikar",
"Simdega",
"Sindhudurg",
"Singrauli",
"Sirmaur",
"Sirohi",
"Sirsa",
"Sitamarhi",
"Sivaganga",
"Siwan",
"Solan",
"Solapur",
"Sonbhadra",
"Sonipat",
"Sonitpur",
"South 24 Parganas",
"South Delhi",
"South Garo Hills",
"South Goa",
"South Sikkim",
"South Tripura",
"South West Delhi",
"Sri Ganganagar",
"Srikakulam",
"Srinagar",
"Subarnapur",
"Sultanpur",
"Sundargarh",
"Supaul",
"Surat",
"Surendranagar",
"Surguja",
"Tamenglong",
"Tarn Taran",
"Tawang",
"Tehri Garhwal",
"Thane",
"Thanjavur",
"The Dangs",
"The Nilgiris",
"Theni",
"Thiruvananthapuram",
"Thoothukudi (Tuticorin)",
"Thoubal",
"Thrissur",
"Tikamgarh",
"Tinsukia",
"Tirap",
"Tiruchirappalli",
"Tirunelveli",
"Tirupathur",
"Tiruppur",
"Tiruvallur",
"Tiruvannamalai",
"Tiruvarur",
"Tonk",
"Tuensang",
"Tumkur",
"Udaipur",
"Udalguri",
"Udham Singh Nagar",
"Udhampur",
"Udupi",
"Ujjain",
"Ukhrul",
"Umaria",
"Una",
"Unakoti",
"Unnao",
"Upper Siang",
"Upper Subansiri",
"Uttar Dinajpur (North Dinajpur)",
"Uttara Kannada (Karwar)",
"Uttarkashi",
"Vadodara",
"Vaishali",
"Valsad",
"Varanasi",
"Vellore",
"Vidisha",
"Viluppuram",
"Virudhunagar",
"Visakhapatnam",
"Vizianagaram",
"Walajapet",
"Warangal",
"Wardha",
"Washim",
"Wayanad",
"West Champaran",
"West Delhi",
"West Garo Hills",
"West Godavari",
"West Kameng",
"West Khasi Hills",
"West Siang",
"West Sikkim",
"West Singhbhum",
"West Tripura",
"Wokha",
"Yadgir",
"Yamunanagar",
"Yanam",
"Yavatmal",
"Zunheboto"
];
